"""Pydantic schemas package."""
from app.schemas.candidate import (
    CandidateBase,
    CandidateCreate,
    CandidateUpdate,
    CandidateDetailResponse,
    CandidateSyncResponse,
    SkillBase,
    SkillCreate,
    SkillUpdate,
    SkillResponse,
    ExperienceBase,
    ExperienceCreate,
    ExperienceUpdate,
    ExperienceResponse,
    ProjectBase,
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    CertificationBase,
    CertificationCreate,
    CertificationUpdate,
    CertificationResponse,
    EducationItem,
    PreferencesItem,
)
from app.schemas.job import (
    RawJobBase,
    RawJobCreate,
    RawJobResponse,
    SkillAliasBase,
    SkillAliasCreate,
    SkillAliasResponse,
    SkillTaxonomyBase,
    SkillTaxonomyCreate,
    SkillTaxonomyResponse,
    JobSkillBase,
    JobSkillResponse,
    JobExtractedData,
    JobBase,
    JobCreate,
    JobUpdate,
    JobResponse,
    JobDetailResponse,
    JobListResponse,
)

from app.schemas.match import (
    JobMatchResponse,
    JobMatchDetailResponse,
    MatchListResponse,
    TopRecommendationItem,
    MatchCalculateRequest,
    BatchCalculateResponse,
    MatchSignalResponse,
    HardFilterResponse,
)

from app.schemas.auth import (
    UserCreate,
    UserLogin,
    UserResponse,
    TokenResponse,
)
from app.schemas.saved_job import (
    SavedJobCreate,
    SavedJobResponse,
)
from app.schemas.resume import (
    EvidenceMapItem,
    CoverLetterResponse,
    TailoredResumeResponse,
    TailoredResumeSummaryResponse,
    TailorResumeRequest,
    ApplicationLogResponse,
    ApplicationSubmitRequest,
    ApplicationStatusUpdateRequest,
)

__all__ = [
    # Auth Schemas
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "TokenResponse",
    # Saved Job Schemas
    "SavedJobCreate",
    "SavedJobResponse",
    # Candidate Schemas (Phase 1)
    "CandidateBase",
    "CandidateCreate",
    "CandidateUpdate",
    "CandidateDetailResponse",
    "CandidateSyncResponse",
    "SkillBase",
    "SkillCreate",
    "SkillUpdate",
    "SkillResponse",
    "ExperienceBase",
    "ExperienceCreate",
    "ExperienceUpdate",
    "ExperienceResponse",
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "CertificationBase",
    "CertificationCreate",
    "CertificationUpdate",
    "CertificationResponse",
    "EducationItem",
    "PreferencesItem",
    # Job Collection Schemas (Phase 2)
    "RawJobBase",
    "RawJobCreate",
    "RawJobResponse",
    "SkillAliasBase",
    "SkillAliasCreate",
    "SkillAliasResponse",
    "SkillTaxonomyBase",
    "SkillTaxonomyCreate",
    "SkillTaxonomyResponse",
    "JobSkillBase",
    "JobSkillResponse",
    "JobExtractedData",
    "JobBase",
    "JobCreate",
    "JobUpdate",
    "JobResponse",
    "JobDetailResponse",
    "JobListResponse",
    # Match Schemas (Phase 3)
    "JobMatchResponse",
    "JobMatchDetailResponse",
    "MatchListResponse",
    "TopRecommendationItem",
    "MatchCalculateRequest",
    "BatchCalculateResponse",
    "MatchSignalResponse",
    "HardFilterResponse",
    # Resume & Application Schemas (Phase 4)
    "EvidenceMapItem",
    "CoverLetterResponse",
    "TailoredResumeResponse",
    "TailoredResumeSummaryResponse",
    "TailorResumeRequest",
    "ApplicationLogResponse",
    "ApplicationSubmitRequest",
    "ApplicationStatusUpdateRequest",
]


